# This is the config file for building Recharge and running its autotest suite
# with Travis-ci.org.

sudo: false

language: python

python:
 - "2.7"

notifications:
  email:
    on_failure: change

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes --quiet conda

install:
  - conda env create -f travis_environment.yml
  - source activate recharge

script:
  - export GDAL_DATA=/home/travis/miniconda2/envs/recharge/share/gdal
  - python setup.py test

notifications:
  slack: nmbgmr:7aYixFDHNlvkIyqqTdvQ7HS9