name: etrm
channels:
- defaults
dependencies:
- affine=2.0.0=py27_0
- alabaster=0.7.8=py27_0
- babel=2.3.3=py27_0
- click=6.7=py27_0
- click-plugins=1.0.3=py27_0
- cligj=0.4.0=py27_0
- curl=7.49.0=1
- cycler=0.10.0=py27_0
- dateutil=2.4.1=py27_0
- docutils=0.12=py27_2
- enum34=1.1.6=py27_0
- freetype=2.5.5=1
- gdal=2.1.0=py27_0
- geos=3.5.0=0
- geotiff=1.4.1=0
- hdf4=4.2.12=0
- hdf5=1.8.17=1
- imagesize=0.7.1=py27_0
- jbig=2.1=0
- jinja2=2.8=py27_1
- jpeg=8d=1
- kealib=1.4.6=0
- libgdal=2.1.0=0
- libnetcdf=4.4.1=0
- libpng=1.6.22=0
- libtiff=4.0.6=2
- markupsafe=0.23=py27_2
- matplotlib=1.5.1=np111py27_0
- mkl=11.3.3=0
- nose=1.3.7=py27_1
- numpy=1.11.0=py27_1
- openssl=1.0.2h=1
- pandas=0.18.1=np111py27_0
- pillow=3.3.0=py27_0
- pip=8.1.2=py27_0
- proj4=4.9.2=0
- pygments=2.1.3=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_3
- python=2.7.11=0
- python-dateutil=2.5.3=py27_0
- pytz=2016.4=py27_0
- pyyaml=3.11=py27_4
- qt=4.8.7=3
- rasterio=0.36.0=np111py27_0
- readline=6.2=2
- reportlab=3.3.0=py27_0
- setuptools=22.0.5=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- snuggs=1.4.0=py27_0
- sphinx=1.4.1=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xerces-c=3.1.4=0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - commonmark==0.5.4
  - future==0.15.2
  - pdfrw==0.2
  - recommonmark==0.4.0
  - sphinx-rtd-theme==0.1.9
prefix: //anaconda/envs/etrm

